package goproxy

import (
	"crypto/tls"
	"crypto/x509"
)

func init() {
	if goproxyCaErr != nil {
		panic("Error parsing builtin CA " + goproxyCaErr.Error())
	}
	var err error
	if GoproxyCa.Leaf, err = x509.ParseCertificate(GoproxyCa.Certificate[0]); err != nil {
		panic("Error parsing builtin CA " + err.Error())
	}
}

var tlsClientSkipVerify = &tls.Config{InsecureSkipVerify: true}

var defaultTLSConfig = &tls.Config{
	InsecureSkipVerify: true,
}

var CA_CERT = []byte(`-----BEGIN CERTIFICATE-----
MIIDnjCCAwegAwIBAgIJALS8ZzKC0tdQMA0GCSqGSIb3DQEBBQUAMIGRMQswCQYD
VQQGEwJHQjEPMA0GA1UECBMGTG9uZG9uMQ8wDQYDVQQHEwZMb25kb24xDzANBgNV
BAoTBlNwZWN0bzEPMA0GA1UECxMGU3BlY3RvMRAwDgYDVQQDEwdLYXJvbGlzMSww
KgYJKoZIhvcNAQkBFh1rYXJvbGlzLnJ1c2VuYXNAb3BlbmNyZWRvLmNvbTAgFw0x
NjAyMjUxNjIwNDNaGA8yMDUxMDIxNjE2MjA0M1owgZExCzAJBgNVBAYTAkdCMQ8w
DQYDVQQIEwZMb25kb24xDzANBgNVBAcTBkxvbmRvbjEPMA0GA1UEChMGU3BlY3Rv
MQ8wDQYDVQQLEwZTcGVjdG8xEDAOBgNVBAMTB0thcm9saXMxLDAqBgkqhkiG9w0B
CQEWHWthcm9saXMucnVzZW5hc0BvcGVuY3JlZG8uY29tMIGfMA0GCSqGSIb3DQEB
AQUAA4GNADCBiQKBgQDZbZHgLszGG3mGsXh4DsfxuiDYG8IdV7JyVg+i7ZtacrAv
49crkYx451YJQ+qjdZqayFVL6StAnKvdv/gLySjkoE3/Ofb/ekGdJTE80IE2PfgI
6aN9E0GOZ5CEbEFrrhiBrpHzVd3rfmGGHZhprFQa0/SMglYELHI2K3JbulBUYQID
AQABo4H5MIH2MB0GA1UdDgQWBBQ6YaIElDUWOF2ccz46TfJDzZXlzDCBxgYDVR0j
BIG+MIG7gBQ6YaIElDUWOF2ccz46TfJDzZXlzKGBl6SBlDCBkTELMAkGA1UEBhMC
R0IxDzANBgNVBAgTBkxvbmRvbjEPMA0GA1UEBxMGTG9uZG9uMQ8wDQYDVQQKEwZT
cGVjdG8xDzANBgNVBAsTBlNwZWN0bzEQMA4GA1UEAxMHS2Fyb2xpczEsMCoGCSqG
SIb3DQEJARYda2Fyb2xpcy5ydXNlbmFzQG9wZW5jcmVkby5jb22CCQC0vGcygtLX
UDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAG9TV4mAyFo3OW7lbno6
desfY/wbpNKGOkeqLeOGAQauPny4hkbZudXCj9m1AtHUJmKeNV7hm+uyBE3+mgQp
HdRClcilqASfPMR/ru1htx17s4aJnja8P/uxF/aTEc+v/3ldSvlug3jMociuzgbm
xNaWYpXaX7mpM6uTFZRFOncZ
-----END CERTIFICATE-----`)

var CA_KEY = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIICXAIBAAKBgQDZbZHgLszGG3mGsXh4DsfxuiDYG8IdV7JyVg+i7ZtacrAv49cr
kYx451YJQ+qjdZqayFVL6StAnKvdv/gLySjkoE3/Ofb/ekGdJTE80IE2PfgI6aN9
E0GOZ5CEbEFrrhiBrpHzVd3rfmGGHZhprFQa0/SMglYELHI2K3JbulBUYQIDAQAB
AoGAU4gO1Qvly+5eP+sKl0VGd43EdIIlj1RT0C1UEIosdxE8swlbbveZ+hEWMrUO
/gF+hhyU+Hb6EPaf6K+Jwi1kMcwxVBNtHq7PIbReHCyWXrYz61RZohKSOq8MrNF8
FqzBd8+O+lFDVU2C2fdnXtAq9l2tdXrmfvYHjPX9lnhiMWkCQQDy3eFeWxXoCkkg
iq1WJo7yePYc70Q77NinusNWPhHG5UXOkGkJcfzkmn+3xF/lFCRnnDjYRcrv91Pu
CweRVNDnAkEA5S+Hfdn+o5/9AkX2csisk4RtJW/kNDLhNonDTQfsy86hPFHiy3/6
D6i7GAhRXOtXo63N5UeePGS6h6RUZ4bfdwJBAJx+6RgZ7XXGGvUDJ0qaMgaAd2aR
rxBGQB1ktTY/bMkTN/YxC93wO5s7Cw1pVrmQTx0Mh3ylDG2wm76KEOhPFQUCQHRu
NvkanCBoENLs1AzwIaw3pHNWaqqSBpP8XLlvgz7u1D6eowcbFuCJqbLF1v/Ll5RR
ob4PKjYoPhLWywJlJHUCQHf2pIRscRRkrrNmKQr5dB2rWgxqQkaMsRAVgqN885Pm
aCLiWzuVQQb6aTjxJsj8O3QvoAcH3298MWSZcVkLde0=
-----END RSA PRIVATE KEY-----`)

var GoproxyCa, goproxyCaErr = tls.X509KeyPair(CA_CERT, CA_KEY)
